version: '2'
services:
 weather-reporter:
    environment:
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - DEBUG=${DEBUG}
    build: .
    ports:
      - "5006:5006"
    hostname: weather-reporter
    container_name: weather-reporter
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  default:
    external: true
    name: weather-app-network
