version: '3.7'

services:

  react-frontend:
    container_name: react-frontend
    build:
      context: ./react_app
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - "1000:80"
    environment:
      - NODE_ENV=development
