version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafkanet

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.1.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
<<<<<<< HEAD
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
=======
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 5135825
      KAFKA_CFG_MAX_REQUEST_SIZE: 5135825
      KAFFA_CFG_SO_SNDBUF: 5135825
      KAFFA_CFG_SO_RCVBUF: 5135825
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 5135825
      KAFKA_MESSAGE_MAX_BYTES: 5135825
>>>>>>> 867fa4908bb305a8593ecaecd86d537783fd0aa5
    networks:
      - kafkanet

  kafka-init:
    image: 'confluentinc/cp-kafka:5.1.1'
    hostname: kafka-init
    container_name: kafka-init
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
        cub kafka-ready -b kafka:9093 1 20 && \
        echo Creating kafka-topics... && \
        kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic REQUEST_STATIONS && \
        kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic RADAR_STATIONS && \
        kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic REQUEST_REPORT && \
        kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic WEATHER_REPORT'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    networks:
      - kafkanet

networks:
  kafkanet:
    name: kafka-net
    driver: bridge