version: "3.9"

services:
  library-api:
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    container_name: gateway_node
    #volumes:
    #  - /app/node_modules
    #  - ./gateway:/app
    ports:
      - 5000:5000

    environment:
      NODE_ENV: ${NODE_ENV}


networks:
  default:
    external: true
    name: weather-app-network