version: "3"

networks:
  weather-app-network:
    name: weather-app-network
    driver: bridge
    
services:
  database-connect:
    image: 'database-connect:latest'
    container_name: database-connect
    ports:
      - '8082:8082'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - weather-app-network
  
  audit:
    image: 'audit:latest'
    container_name: audit-micro
    ports:
      - '8084:8084'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - weather-app-network


  authentication:
    image: 'authentication:latest'
    container_name: authentication-micro
    ports:
      - '8081:8081'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - weather-app-network
      
  mongodb:
    image: mongo:5.0
    hostname: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=PROJECT1-ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=Project1-ADS
    networks:
      - weather-app-network
