version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/scapsulators/react_app # directory where steps will run

    docker: # run the steps with Docker
      - image: cimg/node:17.4.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
    
      - add_ssh_keys:
          fingerprints:
            - "a9:e3:cc:51:62:6b:9c:36:e0:51:a6:5f:ec:27:30:8f"

      - checkout: # check out source code to working directory
         path: ~/scapsulators
         
      - run: node --version
      
      
      - setup_remote_docker:
          version: 19.03.13
              
      - run:
            name: Build Success
            when: on_success
            command: |
              docker --version
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker build -t scapsulators/nasa-react-app:0.0.1 .
              docker push scapsulators/nasa-react-app:0.0.1
              ssh -oStrictHostKeyChecking=no shubhpatr@scapsulators.ignorelist.com -q <<'EOL'
                  sudo su -
                  cd scapsulators/kubernetes
                  kubectl delete -f react.yaml
                  git pull
                  kubectl apply -f react.yaml
              EOL
              
              
      - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building <application_name> $CIRCLE_BRANCH"
        
     
