version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~/scapsulators/react_app # directory where steps will run

    docker: # run the steps with Docker
      - image: cimg/node:17.4.0 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout: # check out source code to working directory
         path: ~/scapsulators
         
      - run: node --version
      
               # clearing the cache
      - run: npm cache clear --force
          # - run: rm package-lock.json
      - run: npm install
              
      - run:
            name: Build Success
            when: on_success
            command: |
              docker --version
              docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
              docker build -t <docker_account>/<application_name>:0.0.1 .
              docker push <docker_account>/<application_name>:0.0.1
              echo "Docker build made sucessfully!! for <application_name> $CIRCLE_BRANCH"
      - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building <application_name> $CIRCLE_BRANCH"
        
     