apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
  labels:
    app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit-micro
        image: scapsulators/audit-service:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: audit-micro
spec:
  selector:
    app: audit
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
