apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-service-deployment
  labels:
    app: caching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caching-service
  template:
    metadata:
      labels:
        app: caching-service
    spec:
      containers:
      - name: caching-service
        image: scapsulators/caching:0.0.1
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: caching-service
spec:
  selector:
    app: caching-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086