apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react-frontend
        image: scapsulators/nasa-react-app:0.0.1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: react
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001