spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092,kafka:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    
    data:
        mongodb:
            host: mongodb
            port: 27017
            database: mygrocerylist

server:
    port: 8082